version: '3'
services:
  php:
    image: php:8.0-fpm
    healthcheck:
      test: ["CMD", "php", "-m"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork

  nginx:
    image: nginx:1.8
    depends_on:
      - php
      - mysql
    ports:
      - 8008:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/info.php"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: Adminti1601
      MYSQL_DATABASE: devopsdb

networks:
  mynetwork:

