version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK'"]
      interval: 5s
      timeout: 3s
      retries: 3

  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: 28a88508980a8538cff376ab2ab91774e56098f5602a5200a73f82f9fb5d4193

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - php
      - mysql
    ports:
      - 8008:8008
    networks:
      - app_network

networks:
  app_network:

