name: Docker Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-tryouts .
     
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push Docker image
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-tryouts ${{ secrets.DOCKERHUB_USERNAME }}/devops-tryouts:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-tryouts:latest

